name: Verify dependency licenses

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  licensing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          version: 14
      - run: sudo gem install license_finder
      - run: yarn install && composer install
      - run: license_finder
